version: '3.8'
services:
  web:
    container_name: DevGitlab
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'yourhostname.org'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #Gitlab configure
        external_url 'https://www.gitlab.com
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['gitlab_default_theme'] = 2
        #Send outgoing email via the SMTP container:
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.mail.ru"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_domain'] = "mail.ru"
        gitlab_rails['smtp_user_name'] = "xxxxx"
        gitlab_rails['smtp_password'] = "xxxxx"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false
        gitlab_rails['smtp_ca_file'] = '/var/opt/gitlab/reg_mail_ru.pem'
        #Nginx force redirect to Https
        nginx['redirect_http_to_https'] = true
        registry_nginx['redirect_http_to_https'] = true
        mattermost_nginx['redirect_http_to_https'] = true
        postgresql['shared_buffers'] = "1024MB"
    ports:
      - 'IP:25:25'
      - 'IP:80:80'
      - 'IP:443:443'
      - 'IP:2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
